# Generated by Django 2.1.5 on 2019-04-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.CharField(max_length=30)),
                ('car_number', models.CharField(max_length=30)),
                ('province', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=30)),
                ('chassis_number', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('car_cc', models.IntegerField()),
                ('car_type', models.CharField(max_length=30)),
                ('sit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_id', models.CharField(max_length=30)),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=200, null=True)),
                ('province', models.CharField(max_length=30)),
                ('zipcode', models.CharField(max_length=5)),
                ('id_card', models.CharField(max_length=13)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('cus_type', models.IntegerField(default=1)),
            ],
        ),
    ]
