# Generated by Django 2.1.5 on 2019-05-27 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_cc',
            field=models.CharField(max_length=30),
        ),
    ]
