# Generated by Django 2.1.5 on 2019-02-25 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.CharField(max_length=30)),
                ('car_number', models.CharField(max_length=30)),
                ('province', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=30)),
                ('chassis_number', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('car_cc', models.CharField(max_length=30)),
                ('car_type', models.CharField(max_length=30)),
                ('sit', models.IntegerField()),
            ],
        ),
    ]
