# Generated by Django 2.1.5 on 2019-02-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_cc',
            field=models.IntegerField(),
        ),
    ]
