# Generated by Django 2.1.5 on 2019-02-07 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_code', models.CharField(max_length=30)),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('id_card', models.CharField(max_length=13)),
                ('phone1', models.CharField(max_length=15)),
                ('phone2', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('address', models.CharField(max_length=200)),
                ('remark', models.CharField(max_length=200)),
            ],
        ),
    ]
