# Generated by Django 2.1.5 on 2019-05-10 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('id_card', models.CharField(max_length=13)),
                ('phone1', models.CharField(max_length=15)),
                ('phone2', models.CharField(max_length=15, null=True)),
                ('email', models.EmailField(max_length=30, null=True)),
                ('address', models.CharField(max_length=200)),
                ('remark', models.CharField(max_length=200, null=True)),
                ('role', models.CharField(default='broker', max_length=30)),
                ('zipcode', models.CharField(max_length=5, null=True)),
                ('sub_district', models.CharField(max_length=30, null=True)),
                ('distinct', models.CharField(max_length=30, null=True)),
                ('province', models.CharField(max_length=30, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
