# Generated by Django 2.1.5 on 2019-05-19 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': [('is_admin', 'Role is admin')]},
        ),
    ]
