# Generated by Django 2.1.5 on 2019-04-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone2',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='remark',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
