# Generated by Django 2.1.5 on 2019-04-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_control', '0002_auto_20190424_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='distinct',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='province',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='sub_district',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='zipcode',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone2',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
