# Generated by Django 2.1.5 on 2019-02-28 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_control', '0002_employee_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='agent_code',
        ),
    ]
