# Generated by Django 2.1.5 on 2019-02-25 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dec_nbr', models.CharField(max_length=30, null=True)),
                ('agent_code', models.CharField(max_length=30)),
                ('package_id', models.CharField(max_length=30, null=True)),
                ('car_id', models.CharField(max_length=30, null=True)),
                ('cus_id', models.CharField(max_length=30, null=True)),
                ('car_number', models.CharField(max_length=15, null=True)),
                ('company_order', models.CharField(max_length=30, null=True)),
                ('price', models.FloatField()),
                ('total_price', models.FloatField()),
                ('post_date', models.DateField(null=True)),
            ],
        ),
    ]
