# Generated by Django 2.1.5 on 2019-05-10 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tranfer',
            name='Package_id',
        ),
        migrations.RemoveField(
            model_name='tranfer',
            name='emp_id',
        ),
        migrations.DeleteModel(
            name='Tranfer',
        ),
    ]
