# Generated by Django 2.1.5 on 2019-02-25 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insure',
            name='agent_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_control.Employee'),
        ),
    ]
