# Generated by Django 2.1.5 on 2019-02-25 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_auto_20190225_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_id', models.CharField(max_length=30)),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=200, null=True)),
                ('province', models.CharField(max_length=30)),
                ('zipcode', models.CharField(max_length=5)),
                ('id_card', models.CharField(max_length=13)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('doc_nbr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance.Insure')),
            ],
        ),
    ]
