# Generated by Django 2.1.5 on 2019-05-10 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_control', '0001_initial'),
        ('package_control', '0001_initial'),
        ('insurance', '0002_auto_20190510_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tranfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField()),
                ('pic_balance', models.ImageField(upload_to='')),
                ('Package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package_control.Package')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_control.Employee')),
            ],
        ),
    ]
