# Generated by Django 2.1.5 on 2019-02-25 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='doc_nbr',
        ),
        migrations.AlterField(
            model_name='insure',
            name='cus_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
