# Generated by Django 2.1.5 on 2019-05-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0004_insure_confirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tranfer',
            name='pic_balance',
            field=models.ImageField(upload_to='pic_balance'),
        ),
    ]
