# Generated by Django 2.1.5 on 2019-02-25 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0004_auto_20190225_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insure',
            name='car_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Car'),
        ),
    ]
