# Generated by Django 2.1.5 on 2019-05-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0005_auto_20190510_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insure',
            name='confirm',
            field=models.IntegerField(default=2),
        ),
    ]
