# Generated by Django 2.1.5 on 2019-02-25 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('package_control', '__first__'),
        ('insurance', '0005_auto_20190225_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insure',
            name='package_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='package_control.Package'),
        ),
    ]
