# Generated by Django 2.1.5 on 2019-02-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_id', models.CharField(max_length=30)),
                ('package_name', models.CharField(max_length=30)),
                ('company_name', models.CharField(max_length=30)),
                ('package_cc', models.IntegerField()),
                ('package_type', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('detail', models.CharField(max_length=200)),
            ],
        ),
    ]
