# Generated by Django 2.1.5 on 2019-02-25 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0006_auto_20190225_2117'),
        ('package_control', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Package',
            new_name='Package_category',
        ),
    ]
