# Generated by Django 2.1.5 on 2019-05-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='active',
            field=models.IntegerField(default=1),
        ),
    ]
