# Generated by Django 2.1.5 on 2019-02-25 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0006_auto_20190225_2117'),
        ('package_control', '0002_auto_20190225_2120'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Package_category',
            new_name='Package',
        ),
    ]
