# Generated by Django 2.1.5 on 2019-05-11 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_control', '0002_package_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='package_cc',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_type',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
