# Generated by Django 2.1.5 on 2019-05-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_control', '0003_auto_20190511_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='active',
            field=models.IntegerField(default=2),
        ),
    ]
