# Generated by Django 2.1.5 on 2019-02-25 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_control', '0003_auto_20190225_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='company_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='detail',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_type',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
