# Generated by Django 2.1.5 on 2019-03-18 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_control', '0004_auto_20190225_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_name', models.CharField(max_length=30)),
                ('promotion_detail', models.CharField(max_length=200)),
                ('end_date', models.DateField(null=True)),
            ],
        ),
    ]
